/// <reference types="vitest/importMeta" />
declare var describe: any;
declare var it: any;
declare var expect: any;
declare var vi: any;
declare var test: any;
declare var beforeEach: any;
declare var afterEach: any;
declare var beforeAll: any;
declare var afterAll: any;
