import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."_locales" AS ENUM('en');
  CREATE TYPE "public"."enum_users_role" AS ENUM('super_admin', 'none');
  CREATE TYPE "public"."enum_blog_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__blog_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__blog_v_published_locale" AS ENUM('en');
  CREATE TYPE "public"."enum_blog_categories_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__blog_categories_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__blog_categories_v_published_locale" AS ENUM('en');
  CREATE TYPE "public"."enum_site_config_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__site_config_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__site_config_v_published_locale" AS ENUM('en');
  CREATE TYPE "public"."enum_menus_items_children_type" AS ENUM('page', 'custom', 'divider', 'label');
  CREATE TYPE "public"."enum_menus_items_type" AS ENUM('page', 'custom', 'submenu-trigger');
  CREATE TYPE "public"."enum_menus_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__menus_v_version_items_children_type" AS ENUM('page', 'custom', 'divider', 'label');
  CREATE TYPE "public"."enum__menus_v_version_items_type" AS ENUM('page', 'custom', 'submenu-trigger');
  CREATE TYPE "public"."enum__menus_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__menus_v_published_locale" AS ENUM('en');
  CREATE TABLE "ai_logs" (
  	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"model" text,
  	"totalDuration" numeric,
  	"error" text,
  	"totalTokens" numeric,
  	"tokenUsage" jsonb,
  	"user" text,
  	"client" uuid,
  	"cost" double precision DEFAULT '0',
  	"prompt" text,
  	"app" uuid,
  	"creditSource" text DEFAULT 'monthly',
  	"addonId" uuid
  );
  
  CREATE TABLE "app_assets" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"app" uuid,
  	"name" text,
  	"url" text,
  	"size" text,
  	"folderId" text,
  	"thumbnailUrl" text,
  	"duration" numeric,
  	"format" text,
  	"width" numeric,
  	"height" numeric,
  	"createdBy" text,
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"type" text,
  	"updatedAt" timestamp with time zone,
  	"description" jsonb DEFAULT '{}'::jsonb,
  	"deletedAt" timestamp with time zone,
  	"deletedBy" text
  );
  
  CREATE TABLE "app_pages" (
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"slug" text NOT NULL,
  	"lang" text DEFAULT '' NOT NULL,
  	"seo" jsonb DEFAULT '{}'::jsonb,
  	"app" uuid NOT NULL,
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"name" text NOT NULL,
  	"primaryPage" uuid,
  	"blocks" jsonb DEFAULT '[]'::jsonb,
  	"currentEditor" text,
  	"changes" jsonb,
  	"online" boolean DEFAULT false,
  	"parent" uuid,
  	"pageType" text,
  	"lastSaved" timestamp with time zone,
  	"dynamic" boolean DEFAULT false,
  	"libRefId" uuid,
  	"dynamicSlugCustom" text DEFAULT '',
  	"metadata" jsonb DEFAULT '{}'::jsonb,
  	"jsonld" jsonb DEFAULT '{}'::jsonb,
  	"globalJsonLds" jsonb DEFAULT '[]'::jsonb,
  	"links" text,
  	"partialBlocks" text,
  	"designTokens" jsonb,
  	"ai" jsonb DEFAULT '{}'::jsonb,
  	"deletedAt" timestamp with time zone,
  	"deletedBy" text,
  	"createdBy" text,
  	"tracking" jsonb DEFAULT '{}'::jsonb
  );
  
  CREATE TABLE "app_pages_online" (
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"slug" text NOT NULL,
  	"lang" text DEFAULT '' NOT NULL,
  	"seo" jsonb DEFAULT '{}'::jsonb,
  	"app" uuid NOT NULL,
  	"id" uuid PRIMARY KEY NOT NULL,
  	"name" text NOT NULL,
  	"primaryPage" uuid,
  	"blocks" jsonb DEFAULT '[]'::jsonb,
  	"currentEditor" text,
  	"changes" jsonb,
  	"partialBlocks" text,
  	"links" text,
  	"online" boolean DEFAULT true,
  	"pageType" text,
  	"parent" uuid,
  	"lastSaved" timestamp with time zone,
  	"dynamic" boolean DEFAULT false,
  	"libRefId" uuid,
  	"dynamicSlugCustom" text DEFAULT '',
  	"metadata" jsonb DEFAULT '{}'::jsonb,
  	"jsonld" jsonb DEFAULT '{}'::jsonb,
  	"globalJsonLds" jsonb DEFAULT '[]'::jsonb,
  	"designTokens" jsonb,
  	"ai" jsonb DEFAULT '{}'::jsonb,
  	"createdBy" text DEFAULT '',
  	"deletedAt" timestamp with time zone,
  	"deletedBy" text,
  	"tracking" jsonb DEFAULT '{}'::jsonb
  );
  
  CREATE TABLE "app_users" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"user" text,
  	"app" uuid,
  	"role" text,
  	"permissions" jsonb,
  	"status" text DEFAULT 'active' NOT NULL
  );
  
  CREATE TABLE "apps" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"name" text,
  	"user" text,
  	"settings" jsonb DEFAULT '{}'::jsonb,
  	"theme" jsonb DEFAULT '{}'::jsonb,
  	"fallbackLang" text DEFAULT 'en',
  	"languages" jsonb DEFAULT '[]'::jsonb,
  	"changes" jsonb,
  	"deletedAt" timestamp with time zone,
  	"client" uuid,
  	"designTokens" jsonb DEFAULT '{}'::jsonb,
  	"ai" jsonb DEFAULT '{}'::jsonb,
  	"configData" jsonb DEFAULT '{}'::jsonb,
  	"consentConfig" jsonb DEFAULT '{}'::jsonb
  );
  
  CREATE TABLE "apps_online" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"name" text,
  	"user" text,
  	"settings" jsonb DEFAULT '{}'::jsonb,
  	"theme" jsonb DEFAULT '{}'::jsonb,
  	"fallbackLang" text DEFAULT 'en',
  	"languages" jsonb DEFAULT '[]'::jsonb,
  	"changes" jsonb,
  	"apiKey" text,
  	"deletedAt" timestamp with time zone,
  	"client" uuid,
  	"designTokens" jsonb DEFAULT '{}'::jsonb,
  	"ai" jsonb DEFAULT '{}'::jsonb,
  	"configData" jsonb DEFAULT '{}'::jsonb,
  	"consentConfig" jsonb DEFAULT '{}'::jsonb
  );
  
  CREATE TABLE "clients" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"name" text,
  	"status" text DEFAULT 'active',
  	"billingStartDate" date,
  	"startDate" date,
  	"settings" jsonb DEFAULT '{}'::jsonb,
  	"loginHtml" text,
  	"features" jsonb DEFAULT '{}'::jsonb,
  	"paymentConfig" jsonb DEFAULT '{}'::jsonb,
  	"theme" text,
  	"helpHtml" text,
  	"madeWithBadge" text,
  	"superAdmins" jsonb DEFAULT '[]'::jsonb,
  	"ai" jsonb DEFAULT '{"models":[]}'::jsonb,
  	"plansAndAddOns" jsonb DEFAULT '{"plans":[],"addOns":[],"provider":"DODO","paymentEnv":"sandbox"}'::jsonb,
  	"rolesAndPermissions" jsonb DEFAULT '{"admin":{"permissions":{"*":true}},"editor":{"permissions":{"*":false}},"designer":{"permissions":{"*":false}}}'::jsonb,
  	"coreFeatures" jsonb DEFAULT '{"ai":true,"email":false,"api_access":false,"multi_user":false,"export_code":true,"import_html":true,"multilingual":false,"revision_and_restore":false}'::jsonb,
  	"envs" jsonb DEFAULT '{"payment":{"live":{"client":"","server":""},"sandbox":{"client":"","server":""}}}'::jsonb
  );
  
  CREATE TABLE "libraries" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"name" text,
  	"app" uuid,
  	"type" text,
  	"status" text DEFAULT 'active' NOT NULL,
  	"client" uuid
  );
  
  CREATE TABLE "library_items" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"library" uuid,
  	"name" text,
  	"description" text,
  	"blocks" jsonb DEFAULT '[]'::jsonb,
  	"preview" text,
  	"group" text DEFAULT 'general',
  	"user" text,
  	"html" text,
  	"deletedAt" timestamp with time zone,
  	"deletedBy" text,
  	"createdBy" text
  );
  
  CREATE TABLE "library_templates" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
  	"user" text,
  	"name" text,
  	"description" text,
  	"pageId" uuid,
  	"pageType" text,
  	"library" uuid,
  	"preview" text,
  	"deletedAt" timestamp with time zone,
  	"createdBy" text,
  	"deletedBy" text
  );
  
  CREATE TABLE "users_sessions" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"created_at" timestamp(3) with time zone,
  	"expires_at" timestamp(3) with time zone NOT NULL
  );
  
  CREATE TABLE "users" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"first_name" varchar,
  	"last_name" varchar,
  	"role" "enum_users_role" DEFAULT 'none',
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"email" varchar NOT NULL,
  	"reset_password_token" varchar,
  	"reset_password_expiration" timestamp(3) with time zone,
  	"salt" varchar,
  	"hash" varchar,
  	"login_attempts" numeric DEFAULT 0,
  	"lock_until" timestamp(3) with time zone
  );
  
  CREATE TABLE "blog" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"app" varchar,
  	"hero_image_id" uuid,
  	"published_at" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "enum_blog_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "blog_locales" (
  	"title" varchar,
  	"slug" varchar,
  	"content" jsonb DEFAULT '{"root":{"type":"root","children":[{"type":"paragraph","children":[{"type":"text","detail":0,"format":0,"mode":"normal","style":"","text":"","version":1}],"direction":null,"format":"","indent":0,"textFormat":0,"textStyle":"","version":1}],"direction":null,"format":"","indent":0,"version":1}}'::jsonb,
  	"excerpt" varchar,
  	"meta_title" varchar,
  	"meta_description" varchar,
  	"meta_image_id" uuid,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" uuid NOT NULL
  );
  
  CREATE TABLE "blog_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" uuid NOT NULL,
  	"path" varchar NOT NULL,
  	"blog_categories_id" uuid,
  	"users_id" uuid
  );
  
  CREATE TABLE "_blog_v" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"parent_id" uuid,
  	"version_app" varchar,
  	"version_hero_image_id" uuid,
  	"version_published_at" timestamp(3) with time zone,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "enum__blog_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"snapshot" boolean,
  	"published_locale" "enum__blog_v_published_locale",
  	"latest" boolean
  );
  
  CREATE TABLE "_blog_v_locales" (
  	"version_title" varchar,
  	"version_slug" varchar,
  	"version_content" jsonb DEFAULT '{"root":{"type":"root","children":[{"type":"paragraph","children":[{"type":"text","detail":0,"format":0,"mode":"normal","style":"","text":"","version":1}],"direction":null,"format":"","indent":0,"textFormat":0,"textStyle":"","version":1}],"direction":null,"format":"","indent":0,"version":1}}'::jsonb,
  	"version_excerpt" varchar,
  	"version_meta_title" varchar,
  	"version_meta_description" varchar,
  	"version_meta_image_id" uuid,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" uuid NOT NULL
  );
  
  CREATE TABLE "_blog_v_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" uuid NOT NULL,
  	"path" varchar NOT NULL,
  	"blog_categories_id" uuid,
  	"users_id" uuid
  );
  
  CREATE TABLE "blog_categories" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"app" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "enum_blog_categories_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "blog_categories_locales" (
  	"name" varchar,
  	"slug" varchar,
  	"description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" uuid NOT NULL
  );
  
  CREATE TABLE "_blog_categories_v" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"parent_id" uuid,
  	"version_app" varchar,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "enum__blog_categories_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"snapshot" boolean,
  	"published_locale" "enum__blog_categories_v_published_locale",
  	"latest" boolean
  );
  
  CREATE TABLE "_blog_categories_v_locales" (
  	"version_name" varchar,
  	"version_slug" varchar,
  	"version_description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" uuid NOT NULL
  );
  
  CREATE TABLE "media" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"app" varchar NOT NULL,
  	"deleted_at" timestamp(3) with time zone,
  	"deleted_by" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"url" varchar,
  	"thumbnail_u_r_l" varchar,
  	"filename" varchar,
  	"mime_type" varchar,
  	"filesize" numeric,
  	"width" numeric,
  	"height" numeric,
  	"focal_x" numeric,
  	"focal_y" numeric
  );
  
  CREATE TABLE "media_locales" (
  	"alt" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" uuid NOT NULL
  );
  
  CREATE TABLE "site_config_social_links" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"platform" varchar,
  	"url" varchar
  );
  
  CREATE TABLE "site_config" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"app" varchar,
  	"logo_id" uuid,
  	"favicon_id" uuid,
  	"contact_email" varchar,
  	"contact_phone" varchar,
  	"physical_address_zip" varchar,
  	"physical_address_location" geometry(Point),
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "enum_site_config_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "site_config_locales" (
  	"name" varchar,
  	"tagline" varchar,
  	"physical_address_address_line1" varchar,
  	"physical_address_address_line2" varchar,
  	"physical_address_city" varchar,
  	"physical_address_state" varchar,
  	"privacy_policy_page" varchar,
  	"terms_of_services_page" varchar,
  	"meta_title" varchar,
  	"meta_description" varchar,
  	"meta_image_id" uuid,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" uuid NOT NULL
  );
  
  CREATE TABLE "_site_config_v_version_social_links" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"platform" varchar,
  	"url" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_site_config_v" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"parent_id" uuid,
  	"version_app" varchar,
  	"version_logo_id" uuid,
  	"version_favicon_id" uuid,
  	"version_contact_email" varchar,
  	"version_contact_phone" varchar,
  	"version_physical_address_zip" varchar,
  	"version_physical_address_location" geometry(Point),
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "enum__site_config_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"snapshot" boolean,
  	"published_locale" "enum__site_config_v_published_locale",
  	"latest" boolean
  );
  
  CREATE TABLE "_site_config_v_locales" (
  	"version_name" varchar,
  	"version_tagline" varchar,
  	"version_physical_address_address_line1" varchar,
  	"version_physical_address_address_line2" varchar,
  	"version_physical_address_city" varchar,
  	"version_physical_address_state" varchar,
  	"version_privacy_policy_page" varchar,
  	"version_terms_of_services_page" varchar,
  	"version_meta_title" varchar,
  	"version_meta_description" varchar,
  	"version_meta_image_id" uuid,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" uuid NOT NULL
  );
  
  CREATE TABLE "form_submissions" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"app" varchar NOT NULL,
  	"form_name" varchar NOT NULL,
  	"page_url" varchar,
  	"form_data" jsonb NOT NULL,
  	"additional_data" jsonb,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "menus_items_children" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"type" "enum_menus_items_children_type" DEFAULT 'page',
  	"url" varchar,
  	"open_in_new_tab" boolean DEFAULT false,
  	"icon" varchar
  );
  
  CREATE TABLE "menus_items_children_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  
  CREATE TABLE "menus_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"type" "enum_menus_items_type" DEFAULT 'page',
  	"url" varchar,
  	"open_in_new_tab" boolean DEFAULT false,
  	"icon" varchar
  );
  
  CREATE TABLE "menus_items_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  
  CREATE TABLE "menus" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"app" varchar,
  	"name" varchar,
  	"description" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "enum_menus_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "_menus_v_version_items_children" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"type" "enum__menus_v_version_items_children_type" DEFAULT 'page',
  	"url" varchar,
  	"open_in_new_tab" boolean DEFAULT false,
  	"icon" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_menus_v_version_items_children_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" uuid NOT NULL
  );
  
  CREATE TABLE "_menus_v_version_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"type" "enum__menus_v_version_items_type" DEFAULT 'page',
  	"url" varchar,
  	"open_in_new_tab" boolean DEFAULT false,
  	"icon" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_menus_v_version_items_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" uuid NOT NULL
  );
  
  CREATE TABLE "_menus_v" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"parent_id" uuid,
  	"version_app" varchar,
  	"version_name" varchar,
  	"version_description" varchar,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "enum__menus_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"snapshot" boolean,
  	"published_locale" "enum__menus_v_published_locale",
  	"latest" boolean
  );
  
  CREATE TABLE "payload_kv" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"key" varchar NOT NULL,
  	"data" jsonb NOT NULL
  );
  
  CREATE TABLE "payload_locked_documents" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"global_slug" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "payload_locked_documents_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" uuid NOT NULL,
  	"path" varchar NOT NULL,
  	"users_id" uuid,
  	"blog_id" uuid,
  	"blog_categories_id" uuid,
  	"media_id" uuid,
  	"site_config_id" uuid,
  	"form_submissions_id" uuid,
  	"menus_id" uuid
  );
  
  CREATE TABLE "payload_preferences" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"key" varchar,
  	"value" jsonb,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "payload_preferences_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" uuid NOT NULL,
  	"path" varchar NOT NULL,
  	"users_id" uuid
  );
  
  CREATE TABLE "payload_migrations" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"name" varchar,
  	"batch" numeric,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "ai_logs" ADD CONSTRAINT "ai_logs_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "ai_logs" ADD CONSTRAINT "ai_logs_client_fkey" FOREIGN KEY ("client") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "app_assets" ADD CONSTRAINT "app_assets_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "app_pages" ADD CONSTRAINT "app_pages_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "app_pages" ADD CONSTRAINT "app_pages_parent_fkey" FOREIGN KEY ("parent") REFERENCES "public"."app_pages"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "app_pages_online" ADD CONSTRAINT "app_pages_online_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "app_users" ADD CONSTRAINT "app_users_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "apps" ADD CONSTRAINT "apps_client_fkey" FOREIGN KEY ("client") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "apps_online" ADD CONSTRAINT "apps_online_client_fkey" FOREIGN KEY ("client") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "libraries" ADD CONSTRAINT "libraries_app_fkey" FOREIGN KEY ("app") REFERENCES "public"."apps"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "library_items" ADD CONSTRAINT "library_items_library_fkey" FOREIGN KEY ("library") REFERENCES "public"."libraries"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "library_templates" ADD CONSTRAINT "library_templates_library_fkey" FOREIGN KEY ("library") REFERENCES "public"."libraries"("id") ON DELETE no action ON UPDATE no action;
  ALTER TABLE "users_sessions" ADD CONSTRAINT "users_sessions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "blog" ADD CONSTRAINT "blog_hero_image_id_media_id_fk" FOREIGN KEY ("hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "blog_locales" ADD CONSTRAINT "blog_locales_meta_image_id_media_id_fk" FOREIGN KEY ("meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "blog_locales" ADD CONSTRAINT "blog_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."blog"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "blog_rels" ADD CONSTRAINT "blog_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."blog"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "blog_rels" ADD CONSTRAINT "blog_rels_blog_categories_fk" FOREIGN KEY ("blog_categories_id") REFERENCES "public"."blog_categories"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "blog_rels" ADD CONSTRAINT "blog_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_blog_v" ADD CONSTRAINT "_blog_v_parent_id_blog_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."blog"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_blog_v" ADD CONSTRAINT "_blog_v_version_hero_image_id_media_id_fk" FOREIGN KEY ("version_hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_blog_v_locales" ADD CONSTRAINT "_blog_v_locales_version_meta_image_id_media_id_fk" FOREIGN KEY ("version_meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_blog_v_locales" ADD CONSTRAINT "_blog_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_blog_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_blog_v_rels" ADD CONSTRAINT "_blog_v_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."_blog_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_blog_v_rels" ADD CONSTRAINT "_blog_v_rels_blog_categories_fk" FOREIGN KEY ("blog_categories_id") REFERENCES "public"."blog_categories"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_blog_v_rels" ADD CONSTRAINT "_blog_v_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "blog_categories_locales" ADD CONSTRAINT "blog_categories_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."blog_categories"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_blog_categories_v" ADD CONSTRAINT "_blog_categories_v_parent_id_blog_categories_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."blog_categories"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_blog_categories_v_locales" ADD CONSTRAINT "_blog_categories_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_blog_categories_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "media_locales" ADD CONSTRAINT "media_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."media"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_config_social_links" ADD CONSTRAINT "site_config_social_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_config"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_config" ADD CONSTRAINT "site_config_logo_id_media_id_fk" FOREIGN KEY ("logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "site_config" ADD CONSTRAINT "site_config_favicon_id_media_id_fk" FOREIGN KEY ("favicon_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "site_config_locales" ADD CONSTRAINT "site_config_locales_meta_image_id_media_id_fk" FOREIGN KEY ("meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "site_config_locales" ADD CONSTRAINT "site_config_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_config"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_site_config_v_version_social_links" ADD CONSTRAINT "_site_config_v_version_social_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_site_config_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_site_config_v" ADD CONSTRAINT "_site_config_v_parent_id_site_config_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."site_config"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_site_config_v" ADD CONSTRAINT "_site_config_v_version_logo_id_media_id_fk" FOREIGN KEY ("version_logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_site_config_v" ADD CONSTRAINT "_site_config_v_version_favicon_id_media_id_fk" FOREIGN KEY ("version_favicon_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_site_config_v_locales" ADD CONSTRAINT "_site_config_v_locales_version_meta_image_id_media_id_fk" FOREIGN KEY ("version_meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_site_config_v_locales" ADD CONSTRAINT "_site_config_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_site_config_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "menus_items_children" ADD CONSTRAINT "menus_items_children_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."menus_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "menus_items_children_locales" ADD CONSTRAINT "menus_items_children_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."menus_items_children"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "menus_items" ADD CONSTRAINT "menus_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."menus"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "menus_items_locales" ADD CONSTRAINT "menus_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."menus_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_menus_v_version_items_children" ADD CONSTRAINT "_menus_v_version_items_children_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_menus_v_version_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_menus_v_version_items_children_locales" ADD CONSTRAINT "_menus_v_version_items_children_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_menus_v_version_items_children"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_menus_v_version_items" ADD CONSTRAINT "_menus_v_version_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_menus_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_menus_v_version_items_locales" ADD CONSTRAINT "_menus_v_version_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_menus_v_version_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_menus_v" ADD CONSTRAINT "_menus_v_parent_id_menus_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."menus"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."payload_locked_documents"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_blog_fk" FOREIGN KEY ("blog_id") REFERENCES "public"."blog"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_blog_categories_fk" FOREIGN KEY ("blog_categories_id") REFERENCES "public"."blog_categories"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_media_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_site_config_fk" FOREIGN KEY ("site_config_id") REFERENCES "public"."site_config"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_form_submissions_fk" FOREIGN KEY ("form_submissions_id") REFERENCES "public"."form_submissions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_menus_fk" FOREIGN KEY ("menus_id") REFERENCES "public"."menus"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."payload_preferences"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "ai_logs_addon_id_idx" ON "ai_logs" USING btree ("addonId" uuid_ops);
  CREATE INDEX "ai_logs_credit_source_idx" ON "ai_logs" USING btree ("creditSource" text_ops);
  CREATE INDEX "idx_app_pages_app_slug" ON "app_pages" USING btree ("app","slug");
  CREATE INDEX "idx_app_pages_online_app_slug" ON "app_pages_online" USING btree ("app","slug");
  CREATE INDEX "users_sessions_order_idx" ON "users_sessions" USING btree ("_order");
  CREATE INDEX "users_sessions_parent_id_idx" ON "users_sessions" USING btree ("_parent_id");
  CREATE INDEX "users_updated_at_idx" ON "users" USING btree ("updated_at");
  CREATE INDEX "users_created_at_idx" ON "users" USING btree ("created_at");
  CREATE UNIQUE INDEX "users_email_idx" ON "users" USING btree ("email");
  CREATE INDEX "blog_hero_image_idx" ON "blog" USING btree ("hero_image_id");
  CREATE INDEX "blog_updated_at_idx" ON "blog" USING btree ("updated_at");
  CREATE INDEX "blog_created_at_idx" ON "blog" USING btree ("created_at");
  CREATE INDEX "blog__status_idx" ON "blog" USING btree ("_status");
  CREATE UNIQUE INDEX "blog_slug_idx" ON "blog_locales" USING btree ("slug","_locale");
  CREATE INDEX "blog_meta_meta_image_idx" ON "blog_locales" USING btree ("meta_image_id","_locale");
  CREATE UNIQUE INDEX "blog_locales_locale_parent_id_unique" ON "blog_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "blog_rels_order_idx" ON "blog_rels" USING btree ("order");
  CREATE INDEX "blog_rels_parent_idx" ON "blog_rels" USING btree ("parent_id");
  CREATE INDEX "blog_rels_path_idx" ON "blog_rels" USING btree ("path");
  CREATE INDEX "blog_rels_blog_categories_id_idx" ON "blog_rels" USING btree ("blog_categories_id");
  CREATE INDEX "blog_rels_users_id_idx" ON "blog_rels" USING btree ("users_id");
  CREATE INDEX "_blog_v_parent_idx" ON "_blog_v" USING btree ("parent_id");
  CREATE INDEX "_blog_v_version_version_hero_image_idx" ON "_blog_v" USING btree ("version_hero_image_id");
  CREATE INDEX "_blog_v_version_version_updated_at_idx" ON "_blog_v" USING btree ("version_updated_at");
  CREATE INDEX "_blog_v_version_version_created_at_idx" ON "_blog_v" USING btree ("version_created_at");
  CREATE INDEX "_blog_v_version_version__status_idx" ON "_blog_v" USING btree ("version__status");
  CREATE INDEX "_blog_v_created_at_idx" ON "_blog_v" USING btree ("created_at");
  CREATE INDEX "_blog_v_updated_at_idx" ON "_blog_v" USING btree ("updated_at");
  CREATE INDEX "_blog_v_snapshot_idx" ON "_blog_v" USING btree ("snapshot");
  CREATE INDEX "_blog_v_published_locale_idx" ON "_blog_v" USING btree ("published_locale");
  CREATE INDEX "_blog_v_latest_idx" ON "_blog_v" USING btree ("latest");
  CREATE INDEX "_blog_v_version_version_slug_idx" ON "_blog_v_locales" USING btree ("version_slug","_locale");
  CREATE INDEX "_blog_v_version_meta_version_meta_image_idx" ON "_blog_v_locales" USING btree ("version_meta_image_id","_locale");
  CREATE UNIQUE INDEX "_blog_v_locales_locale_parent_id_unique" ON "_blog_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_v_rels_order_idx" ON "_blog_v_rels" USING btree ("order");
  CREATE INDEX "_blog_v_rels_parent_idx" ON "_blog_v_rels" USING btree ("parent_id");
  CREATE INDEX "_blog_v_rels_path_idx" ON "_blog_v_rels" USING btree ("path");
  CREATE INDEX "_blog_v_rels_blog_categories_id_idx" ON "_blog_v_rels" USING btree ("blog_categories_id");
  CREATE INDEX "_blog_v_rels_users_id_idx" ON "_blog_v_rels" USING btree ("users_id");
  CREATE INDEX "blog_categories_updated_at_idx" ON "blog_categories" USING btree ("updated_at");
  CREATE INDEX "blog_categories_created_at_idx" ON "blog_categories" USING btree ("created_at");
  CREATE INDEX "blog_categories__status_idx" ON "blog_categories" USING btree ("_status");
  CREATE UNIQUE INDEX "blog_categories_slug_idx" ON "blog_categories_locales" USING btree ("slug","_locale");
  CREATE UNIQUE INDEX "blog_categories_locales_locale_parent_id_unique" ON "blog_categories_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_blog_categories_v_parent_idx" ON "_blog_categories_v" USING btree ("parent_id");
  CREATE INDEX "_blog_categories_v_version_version_updated_at_idx" ON "_blog_categories_v" USING btree ("version_updated_at");
  CREATE INDEX "_blog_categories_v_version_version_created_at_idx" ON "_blog_categories_v" USING btree ("version_created_at");
  CREATE INDEX "_blog_categories_v_version_version__status_idx" ON "_blog_categories_v" USING btree ("version__status");
  CREATE INDEX "_blog_categories_v_created_at_idx" ON "_blog_categories_v" USING btree ("created_at");
  CREATE INDEX "_blog_categories_v_updated_at_idx" ON "_blog_categories_v" USING btree ("updated_at");
  CREATE INDEX "_blog_categories_v_snapshot_idx" ON "_blog_categories_v" USING btree ("snapshot");
  CREATE INDEX "_blog_categories_v_published_locale_idx" ON "_blog_categories_v" USING btree ("published_locale");
  CREATE INDEX "_blog_categories_v_latest_idx" ON "_blog_categories_v" USING btree ("latest");
  CREATE INDEX "_blog_categories_v_version_version_slug_idx" ON "_blog_categories_v_locales" USING btree ("version_slug","_locale");
  CREATE UNIQUE INDEX "_blog_categories_v_locales_locale_parent_id_unique" ON "_blog_categories_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "media_updated_at_idx" ON "media" USING btree ("updated_at");
  CREATE INDEX "media_created_at_idx" ON "media" USING btree ("created_at");
  CREATE UNIQUE INDEX "media_filename_idx" ON "media" USING btree ("filename");
  CREATE UNIQUE INDEX "media_locales_locale_parent_id_unique" ON "media_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "site_config_social_links_order_idx" ON "site_config_social_links" USING btree ("_order");
  CREATE INDEX "site_config_social_links_parent_id_idx" ON "site_config_social_links" USING btree ("_parent_id");
  CREATE INDEX "site_config_logo_idx" ON "site_config" USING btree ("logo_id");
  CREATE INDEX "site_config_favicon_idx" ON "site_config" USING btree ("favicon_id");
  CREATE INDEX "site_config_updated_at_idx" ON "site_config" USING btree ("updated_at");
  CREATE INDEX "site_config_created_at_idx" ON "site_config" USING btree ("created_at");
  CREATE INDEX "site_config__status_idx" ON "site_config" USING btree ("_status");
  CREATE INDEX "site_config_meta_meta_image_idx" ON "site_config_locales" USING btree ("meta_image_id","_locale");
  CREATE UNIQUE INDEX "site_config_locales_locale_parent_id_unique" ON "site_config_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_site_config_v_version_social_links_order_idx" ON "_site_config_v_version_social_links" USING btree ("_order");
  CREATE INDEX "_site_config_v_version_social_links_parent_id_idx" ON "_site_config_v_version_social_links" USING btree ("_parent_id");
  CREATE INDEX "_site_config_v_parent_idx" ON "_site_config_v" USING btree ("parent_id");
  CREATE INDEX "_site_config_v_version_version_logo_idx" ON "_site_config_v" USING btree ("version_logo_id");
  CREATE INDEX "_site_config_v_version_version_favicon_idx" ON "_site_config_v" USING btree ("version_favicon_id");
  CREATE INDEX "_site_config_v_version_version_updated_at_idx" ON "_site_config_v" USING btree ("version_updated_at");
  CREATE INDEX "_site_config_v_version_version_created_at_idx" ON "_site_config_v" USING btree ("version_created_at");
  CREATE INDEX "_site_config_v_version_version__status_idx" ON "_site_config_v" USING btree ("version__status");
  CREATE INDEX "_site_config_v_created_at_idx" ON "_site_config_v" USING btree ("created_at");
  CREATE INDEX "_site_config_v_updated_at_idx" ON "_site_config_v" USING btree ("updated_at");
  CREATE INDEX "_site_config_v_snapshot_idx" ON "_site_config_v" USING btree ("snapshot");
  CREATE INDEX "_site_config_v_published_locale_idx" ON "_site_config_v" USING btree ("published_locale");
  CREATE INDEX "_site_config_v_latest_idx" ON "_site_config_v" USING btree ("latest");
  CREATE INDEX "_site_config_v_version_meta_version_meta_image_idx" ON "_site_config_v_locales" USING btree ("version_meta_image_id","_locale");
  CREATE UNIQUE INDEX "_site_config_v_locales_locale_parent_id_unique" ON "_site_config_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "form_submissions_updated_at_idx" ON "form_submissions" USING btree ("updated_at");
  CREATE INDEX "form_submissions_created_at_idx" ON "form_submissions" USING btree ("created_at");
  CREATE INDEX "menus_items_children_order_idx" ON "menus_items_children" USING btree ("_order");
  CREATE INDEX "menus_items_children_parent_id_idx" ON "menus_items_children" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "menus_items_children_locales_locale_parent_id_unique" ON "menus_items_children_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "menus_items_order_idx" ON "menus_items" USING btree ("_order");
  CREATE INDEX "menus_items_parent_id_idx" ON "menus_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "menus_items_locales_locale_parent_id_unique" ON "menus_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "menus_updated_at_idx" ON "menus" USING btree ("updated_at");
  CREATE INDEX "menus_created_at_idx" ON "menus" USING btree ("created_at");
  CREATE INDEX "menus__status_idx" ON "menus" USING btree ("_status");
  CREATE INDEX "_menus_v_version_items_children_order_idx" ON "_menus_v_version_items_children" USING btree ("_order");
  CREATE INDEX "_menus_v_version_items_children_parent_id_idx" ON "_menus_v_version_items_children" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_menus_v_version_items_children_locales_locale_parent_id_uni" ON "_menus_v_version_items_children_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_menus_v_version_items_order_idx" ON "_menus_v_version_items" USING btree ("_order");
  CREATE INDEX "_menus_v_version_items_parent_id_idx" ON "_menus_v_version_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_menus_v_version_items_locales_locale_parent_id_unique" ON "_menus_v_version_items_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_menus_v_parent_idx" ON "_menus_v" USING btree ("parent_id");
  CREATE INDEX "_menus_v_version_version_updated_at_idx" ON "_menus_v" USING btree ("version_updated_at");
  CREATE INDEX "_menus_v_version_version_created_at_idx" ON "_menus_v" USING btree ("version_created_at");
  CREATE INDEX "_menus_v_version_version__status_idx" ON "_menus_v" USING btree ("version__status");
  CREATE INDEX "_menus_v_created_at_idx" ON "_menus_v" USING btree ("created_at");
  CREATE INDEX "_menus_v_updated_at_idx" ON "_menus_v" USING btree ("updated_at");
  CREATE INDEX "_menus_v_snapshot_idx" ON "_menus_v" USING btree ("snapshot");
  CREATE INDEX "_menus_v_published_locale_idx" ON "_menus_v" USING btree ("published_locale");
  CREATE INDEX "_menus_v_latest_idx" ON "_menus_v" USING btree ("latest");
  CREATE UNIQUE INDEX "payload_kv_key_idx" ON "payload_kv" USING btree ("key");
  CREATE INDEX "payload_locked_documents_global_slug_idx" ON "payload_locked_documents" USING btree ("global_slug");
  CREATE INDEX "payload_locked_documents_updated_at_idx" ON "payload_locked_documents" USING btree ("updated_at");
  CREATE INDEX "payload_locked_documents_created_at_idx" ON "payload_locked_documents" USING btree ("created_at");
  CREATE INDEX "payload_locked_documents_rels_order_idx" ON "payload_locked_documents_rels" USING btree ("order");
  CREATE INDEX "payload_locked_documents_rels_parent_idx" ON "payload_locked_documents_rels" USING btree ("parent_id");
  CREATE INDEX "payload_locked_documents_rels_path_idx" ON "payload_locked_documents_rels" USING btree ("path");
  CREATE INDEX "payload_locked_documents_rels_users_id_idx" ON "payload_locked_documents_rels" USING btree ("users_id");
  CREATE INDEX "payload_locked_documents_rels_blog_id_idx" ON "payload_locked_documents_rels" USING btree ("blog_id");
  CREATE INDEX "payload_locked_documents_rels_blog_categories_id_idx" ON "payload_locked_documents_rels" USING btree ("blog_categories_id");
  CREATE INDEX "payload_locked_documents_rels_media_id_idx" ON "payload_locked_documents_rels" USING btree ("media_id");
  CREATE INDEX "payload_locked_documents_rels_site_config_id_idx" ON "payload_locked_documents_rels" USING btree ("site_config_id");
  CREATE INDEX "payload_locked_documents_rels_form_submissions_id_idx" ON "payload_locked_documents_rels" USING btree ("form_submissions_id");
  CREATE INDEX "payload_locked_documents_rels_menus_id_idx" ON "payload_locked_documents_rels" USING btree ("menus_id");
  CREATE INDEX "payload_preferences_key_idx" ON "payload_preferences" USING btree ("key");
  CREATE INDEX "payload_preferences_updated_at_idx" ON "payload_preferences" USING btree ("updated_at");
  CREATE INDEX "payload_preferences_created_at_idx" ON "payload_preferences" USING btree ("created_at");
  CREATE INDEX "payload_preferences_rels_order_idx" ON "payload_preferences_rels" USING btree ("order");
  CREATE INDEX "payload_preferences_rels_parent_idx" ON "payload_preferences_rels" USING btree ("parent_id");
  CREATE INDEX "payload_preferences_rels_path_idx" ON "payload_preferences_rels" USING btree ("path");
  CREATE INDEX "payload_preferences_rels_users_id_idx" ON "payload_preferences_rels" USING btree ("users_id");
  CREATE INDEX "payload_migrations_updated_at_idx" ON "payload_migrations" USING btree ("updated_at");
  CREATE INDEX "payload_migrations_created_at_idx" ON "payload_migrations" USING btree ("created_at");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "ai_logs" CASCADE;
  DROP TABLE "app_assets" CASCADE;
  DROP TABLE "app_pages" CASCADE;
  DROP TABLE "app_pages_online" CASCADE;
  DROP TABLE "app_users" CASCADE;
  DROP TABLE "apps" CASCADE;
  DROP TABLE "apps_online" CASCADE;
  DROP TABLE "clients" CASCADE;
  DROP TABLE "libraries" CASCADE;
  DROP TABLE "library_items" CASCADE;
  DROP TABLE "library_templates" CASCADE;
  DROP TABLE "users_sessions" CASCADE;
  DROP TABLE "users" CASCADE;
  DROP TABLE "blog" CASCADE;
  DROP TABLE "blog_locales" CASCADE;
  DROP TABLE "blog_rels" CASCADE;
  DROP TABLE "_blog_v" CASCADE;
  DROP TABLE "_blog_v_locales" CASCADE;
  DROP TABLE "_blog_v_rels" CASCADE;
  DROP TABLE "blog_categories" CASCADE;
  DROP TABLE "blog_categories_locales" CASCADE;
  DROP TABLE "_blog_categories_v" CASCADE;
  DROP TABLE "_blog_categories_v_locales" CASCADE;
  DROP TABLE "media" CASCADE;
  DROP TABLE "media_locales" CASCADE;
  DROP TABLE "site_config_social_links" CASCADE;
  DROP TABLE "site_config" CASCADE;
  DROP TABLE "site_config_locales" CASCADE;
  DROP TABLE "_site_config_v_version_social_links" CASCADE;
  DROP TABLE "_site_config_v" CASCADE;
  DROP TABLE "_site_config_v_locales" CASCADE;
  DROP TABLE "form_submissions" CASCADE;
  DROP TABLE "menus_items_children" CASCADE;
  DROP TABLE "menus_items_children_locales" CASCADE;
  DROP TABLE "menus_items" CASCADE;
  DROP TABLE "menus_items_locales" CASCADE;
  DROP TABLE "menus" CASCADE;
  DROP TABLE "_menus_v_version_items_children" CASCADE;
  DROP TABLE "_menus_v_version_items_children_locales" CASCADE;
  DROP TABLE "_menus_v_version_items" CASCADE;
  DROP TABLE "_menus_v_version_items_locales" CASCADE;
  DROP TABLE "_menus_v" CASCADE;
  DROP TABLE "payload_kv" CASCADE;
  DROP TABLE "payload_locked_documents" CASCADE;
  DROP TABLE "payload_locked_documents_rels" CASCADE;
  DROP TABLE "payload_preferences" CASCADE;
  DROP TABLE "payload_preferences_rels" CASCADE;
  DROP TABLE "payload_migrations" CASCADE;
  DROP TYPE "public"."_locales";
  DROP TYPE "public"."enum_users_role";
  DROP TYPE "public"."enum_blog_status";
  DROP TYPE "public"."enum__blog_v_version_status";
  DROP TYPE "public"."enum__blog_v_published_locale";
  DROP TYPE "public"."enum_blog_categories_status";
  DROP TYPE "public"."enum__blog_categories_v_version_status";
  DROP TYPE "public"."enum__blog_categories_v_published_locale";
  DROP TYPE "public"."enum_site_config_status";
  DROP TYPE "public"."enum__site_config_v_version_status";
  DROP TYPE "public"."enum__site_config_v_published_locale";
  DROP TYPE "public"."enum_menus_items_children_type";
  DROP TYPE "public"."enum_menus_items_type";
  DROP TYPE "public"."enum_menus_status";
  DROP TYPE "public"."enum__menus_v_version_items_children_type";
  DROP TYPE "public"."enum__menus_v_version_items_type";
  DROP TYPE "public"."enum__menus_v_version_status";
  DROP TYPE "public"."enum__menus_v_published_locale";`)
}
